version: '3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - domaingraph_database_network
    depends_on:
      - db

  db:
    image: postgres:12.0
    env_file:
      - .env
    networks:
      - domaingraph_database_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/


networks:
  domaingraph_database_network:
    driver: bridge

volumes:
  postgres_data: